# Generated by Django 3.1.6 on 2021-03-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210321_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDeliverd',
            new_name='isDelivered',
        ),
    ]
